name: Sync to COS

on:
  push:
    branches: [ main ]

jobs:
  sync-to-cos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install coscli
      run: |
        curl -fsSL https://github.com/tencentyun/coscli/releases/download/v1.0.6/coscli-v1.0.6-linux-amd64 -o coscli
        chmod +x coscli
        sudo mv coscli /usr/local/bin/coscli
        coscli --version
        
    - name: Configure coscli
      run: |
        coscli config add -b "${{ secrets.COS_BUCKET }}" -r "${{ secrets.COS_REGION }}" -a "github-sync" -e "cos.${{ secrets.COS_REGION }}.myqcloud.com"
        coscli config set --secret_id "${{ secrets.TENCENT_COS_SECRET_ID }}" --secret_key "${{ secrets.TENCENT_COS_SECRET_KEY }}"
        coscli config show   

    - name: Validate configuration
      run: |
        echo "=== 开始验证 ==="
        echo "1. 密钥测试..."
        coscli ls cos://github-sync/ || exit 1

        echo "2. 目录映射测试..."
        mkdir -p test-dir && touch test-dir/test-{1..3}.jpg
        coscli sync test-dir/ cos://github-sync/test-validate/ --recursive --include "test-1.jpg" || exit 1

        echo "3. 权限验证..."
        coscli cp test-dir/test-1.jpg cos://${{ secrets.COS_BUCKET }}/test-validate/ || exit 1
        coscli rm cos://${{ secrets.COS_BUCKET }}/test-validate/test-1.jpg || exit 1

        echo "✅ 所有验证通过"
        

    - name: Prepare sync
      run: |
        # 创建.cosignore文件(如果不存在)
        if [ ! -f .cosignore ]; then
          echo "# 默认忽略规则" > .cosignore
          echo "*.mp4" >> .cosignore
          echo "*.mov" >> .cosignore
          echo "Private/*" >> .cosignore
        fi
        echo "=== Current .cosignore ==="
        cat .cosignore
        
    - name: Run sync # 执行同步
      run: |
        set -x  # 开启调试模式
        coscli sync ./ cos://github-sync/ImageHosting/ \
          --exclude .cosignore \
          --thread-num 5 \
          --delete \ # 同步时删除目标端多余文件
          --snapshot-path .cos-sync-snapshot # 记录同步状态

        # 验证同步结果
        coscli ls cos://github-sync/ --include "*" | head -n 10
        echo "Sync completed at $(date)"

    - name: Upload logs
      if: always()  # 无论成功失败都执行
      run: |
        coscli cp .github/workflows/cos-sync.yml cos://github-sync/Logs/workflow-${{ github.run_id }}.yml
        coscli ls cos://github-sync/ > sync-list.txt
        coscli cp sync-list.txt cos://github-sync/Logs/sync-${{ github.run_id }}.txt

